default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: gschool_user
  password: password

development:
  <<: *default
  database: g2-store_development
  username: gschool_user
  password: password

test:
  <<: *default
  database: g2-store_test
  username: gschool_user
  password: password
